csr.common.name=TSZ-310137521300003
csr.serial.number=1-TST|2-TST|3-6356bb5c-25f1-4503-8429-2cb47f6187cf
csr.organization.identifier=310137521300003
csr.organization.unit.name=Dammam Branch
csr.organization.name=مؤسسة عيسى يوسف العامر للتخليص الجمركي
csr.country.name=SA
csr.invoice.type=1100
csr.location.address=Dammam
csr.industry.business.category=Customs Clearance
